### ISSUE TITLE
TypeError: can only concatenate list (not "str") to list

### ISSUE THREAD

**Issue by michelep** [evilsocket/bleah#9] opened 2017-09-26 09:30 UTC
~/bleah $ python setup.py build
running build
running build_py
running egg_info
writing requirements to bleah.egg-info/requires.txt
writing bleah.egg-info/PKG-INFO
writing top-level names to bleah.egg-info/top_level.txt
writing dependency_links to bleah.egg-info/dependency_links.txt
reading manifest file 'bleah.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '*.pyc'
warning: no previously-included files found matching '.DS_Store'
warning: no previously-included files found matching '.gitignore'
warning: no files found matching 'distribute_setup.py'
writing manifest file 'bleah.egg-info/SOURCES.txt'
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    install_requires     = [ 'bluepy', 'terminaltables' ]
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 52, in run
    self.build_package_data()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 107, in build_package_data
    for package, src_dir, build_dir, filenames in self.data_files:
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 65, in __getattr__
    self.data_files = self._get_data_files()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 79, in _get_data_files
    return list(map(self._get_pkg_data_files, self.packages or ()))
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 91, in _get_pkg_data_files
    for file in self.find_data_files(package, src_dir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 98, in find_data_files
    + self.package_data.get(package, []))
TypeError: can only concatenate list (not "str") to list

**Comment by evilsocket** [comment] 2017-09-26 11:46
duplicate of https://github.com/evilsocket/bleah/issues/4

**Closed by evilsocket** 2017-09-26 11:46 UTC
